[program:websocket]
command=/usr/bin/php /home/tiumwatch/tium-wearable-project-be/artisan websocket:serve
numprocs=1
autostart=true
autorestart=true
user=ubuntu
stdout_logfile=/home/tiumwatch/tium-wearable-project-be/storage/logs/websocket-server.log
