[program:ai_service]
command=/home/tiumwatch/tium-wearable-project-be/ai/venv/bin/python /home/tiumwatch/tium-wearable-project-be/ai/main.py
directory=/home/tiumwatch/tium-wearable-project-be/ai
numprocs=1
autostart=true
autorestart=true
startsecs=5
user=ubuntu
stdout_logfile=/home/tiumwatch/tium-wearable-project-be/storage/logs/ai_service.log
stderr_logfile=/home/tiumwatch/tium-wearable-project-be/storage/logs/ai_service_error.log
redirect_stderr=true
